### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by darthgera123** [BachiLi/redner#111]
On running `two_d_mesh.py` we get 
```Traceback (most recent call last):
  File "two_d_mesh.py", line 50, in <module>
    shape_quad = pyredner.Shape(quad_vertices, quad_indices, None, None, 0)
  File "/home/gera/anaconda3/envs/redner/lib/python3.6/site-packages/pyredner/shape.py", line 181, in __init__
    assert(normals.dtype == torch.float32)
AttributeError: 'int' object has no attribute 'dtype'
```
Similarly on running `joint_material_envmap_sh.py` we get
```
Traceback (most recent call last):
  File "joint_material_envmap_sh.py", line 85, in <module>
    scene = pyredner.Scene(cam, shapes, materials, [], envmap)
  File "/home/gera/anaconda3/envs/redner/lib/python3.6/site-packages/pyredner/scene.py", line 41, in __init__
    for obj in objects:
TypeError: 'EnvironmentMap' object is not iterable
```

**Comment by BachiLi** [comment]
Thanks for reporting! This is fixed by https://github.com/BachiLi/redner/commit/ba053926292af53ee86efb62ecc0684bf095295d

If you want to learn how redner works I would recommend to take a look at the wiki, by the way
https://github.com/BachiLi/redner/wiki

**Comment by BachiLi** [comment]
Closing since this is fixed.
