### ISSUE TITLE
Help testing the Inverse Path Tracing for Joint Material and Lighting Estimation publication

### ISSUE THREAD

**Issue by TheodoreT** [BachiLi/redner#129]
Hi @BachiLi and thank you for this nice repository. Would be easy to give me some guidelines how to test the output from the mentioned publication.

Thanks in advance.

**Comment by ttsesm** [comment]
@BachiLi any help feedback on my question.

**Comment by BachiLi** [comment]
Hey, that CVPR paper used a different renderer and the code was owned by Facebook, so I am not allowed to distribute. I would suggest contacting Dejan Azinović for comparison purpose. 
It should be possible to reproduce what we did there using redner. You can simply set up the scene and optimize the papers using the path tracing mode.

**Comment by ttsesm** [comment]
@BachiLi thanks for the update. Would be easy then to give me some guidance with the steps how to setup/use redner to reproduce similar results from the paper. I am not really interested for comparison purpose, rather than to understand how it works.

Based on this issue https://github.com/BachiLi/redner/issues/34 I will need to run the tests/test_living_room.py example as you have pointed there, is that correct?

Is this an out of the box representation of the paper or modifications need to be applied.

**Comment by ttsesm** [comment]
@BachiLi any feedback regarding my previous message?

**Comment by yzx9** [comment]
~~@BachiLi Is there anything new? I run into the same issue:~~

```
Unsupported Mitsuba scene format: please use a look at transform
Traceback (most recent call last):
  File "./test_living_room.py", line 30, in <module>
    scene = pyredner.load_mitsuba('scenes/living-room-3/scene.xml')
  File "/home/celeste/.conda/envs/pytorch/lib/python3.8/site-packages/pyredner/load_mitsuba.py", line 488, in load_mitsuba
    ret = parse_scene(root, device)
  File "/home/celeste/.conda/envs/pytorch/lib/python3.8/site-packages/pyredner/load_mitsuba.py", line 428, in parse_scene
    cam = parse_camera(child)
  File "/home/celeste/.conda/envs/pytorch/lib/python3.8/site-packages/pyredner/load_mitsuba.py", line 91, in parse_camera
    assert(False)
AssertionError
``` 

Update: Fixed by replace original `scene.xml` file from zip file by `/tests/scenes/living-room-3-scene.xml`
