### ISSUE TITLE
Error running (all) tests

### ISSUE THREAD

**Issue by jayavanth** [BachiLi/redner#2]
$ python3 unit_tests.py  
Traceback (most recent call last):
  File "unit_tests.py", line 1, in <module>
    import pyredner
  File "/home/jay/redner/pyredner/__init__.py", line 7, in <module>
    from .render_pytorch import *
  File "/home/jay/redner/pyredner/render_pytorch.py", line 4, in <module>
    import redner
ImportError: /usr/lib/python3/dist-packages/redner.so: undefined symbol: rtcNewScene

**Comment by jayavanth** [comment]
Fixed it by fixing embree lib paths
