### ISSUE TITLE
"invalid context" when running redner.Scene()

### ISSUE THREAD

**Issue by jpchen** [BachiLi/redner#20]
when i run any of the tutorials i get a Runtime error:
```
Traceback (most recent call last):
  File "tutorials/02_pose_estimation.py", line 84, in <module>
    img = render(0, *scene_args)
  File "/home/jpchen/3d-scene-gen/path_tracer/redner/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context
```

this seems to be coming from the following call: `scene = redner.Scene(camera, shapes, materials, area_lights, envmap, pyredner.get_use_gpu())` by the fact that `envmap` is `None`.  the pointer arithmetic is a bit convoluted so i'm not sure how to go about debugging this. 

Using python 3  on Ubuntu 16.04 with cuda 10.

**Comment by BachiLi** [comment]
What do you mean by envmap is None? Is it None after line 70 of 02_pose_estimation.py?

**Comment by jpchen** [comment]
it is `None` at the call `img = render(0, *scene_args)` in line [99](https://github.com/BachiLi/redner/blob/master/tutorials/01_optimize_single_triangle.py#L99) but this is true no matter which example or test i run.  my C-debugging chops are very rusty so i'm not even sure what the root cause is.

i am only able to install redner (the C library part) after compiling with both gcc5 and gcc7 sequentially. they both throw errors if i just use one during `make install` which makes me wonder if this is due to a bad installation. debuggers dont seem to help at all because of library dependencies. is there a good way to diagnose this?

**Comment by jpchen** [comment]
that error seems to come from embree, so i rolled back to embree v3.2.4 but it still throws the same error.  @BachiLi what version of embree did you test with? the commit pinned in the repo (~v3.5.0) has the same error.

**Comment by SuperShinyEyes** [comment]
I found the same issue. Here's my environment:

```
FROM pytorch/pytorch:1.0-cuda10.0-cudnn7-devel

#-----------------------------------------------------
# Build CMake
RUN curl -L -O https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4.tar.gz && \
    tar -xvzf cmake-3.12.4.tar.gz && \
    rm cmake-3.12.4.tar.gz && \
    cd cmake-3.12.4 && \
    ./bootstrap && make && make install

#-----------------------------------------------------
# ISPC: Embree dependency
# https://github.com/ispc/ispc/blob/master/docker/ubuntu/Dockerfile

# Packages required to build ISPC and Clang.
RUN apt-get -y update && apt-get install -y wget build-essential vim gcc g++ git subversion python m4 bison flex zlib1g-dev ncurses-dev libtinfo-dev libc6-dev-i386 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src

# Fork ispc on github and clone *your* fork.
RUN cd /usr/local/src && git clone https://github.com/ispc/ispc.git

# This is home for Clang builds
RUN mkdir /usr/local/src/llvm

ENV ISPC_HOME=/usr/local/src/ispc
ENV LLVM_HOME=/usr/local/src/llvm

# If you are going to run test for future platforms, go to
# http://www.intel.com/software/sde and download the latest version,
# extract it, add to path and set SDE_HOME.

WORKDIR /usr/local/src/ispc

# Build Clang with all required patches.
# Pass required LLVM_VERSION with --build-arg LLVM_VERSION=<version>.
# By default 5.0 is used.
# Note self-build options, it's required to build clang and ispc with the same compiler,
# i.e. if clang was built by gcc, you may need to use gcc to build ispc (i.e. run "make gcc"),
# or better do clang selfbuild and use it for ispc build as well (i.e. just "make").
# "rm" are just to keep docker image small.
ARG LLVM_VERSION=5.0
RUN ./alloy.py -b --version=$LLVM_VERSION --selfbuild --git && \
    rm -rf $LLVM_HOME/build-$LLVM_VERSION $LLVM_HOME/llvm-$LLVM_VERSION $LLVM_HOME/bin-$LLVM_VERSION_temp $LLVM_HOME/build-$LLVM_VERSION_temp

ENV PATH=$LLVM_HOME/bin-$LLVM_VERSION/bin:$PATH

# Configure ISPC build
RUN mkdir build_$LLVM_VERSION
WORKDIR build_$LLVM_VERSION
RUN cmake ../ -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/usr/local/src/ispc/bin-$LLVM_VERSION

# Build ISPC
RUN make ispc -j8 && make install
WORKDIR ../
RUN rm -rf build_$LLVM_VERSION


#-----------------------------------------------------
# Build Redner

RUN apt-get update && apt-get install -y \
RUN conda install --yes pybind11 numpy scikit-image
    libtbb-dev \ 
    pkg-config \ 
    libglfw3-dev \
    libopenexr-dev \ 
    libopenimageio-dev \
    ranger

# Upgrade to gcc 7
# https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5
RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt update && \
    apt install g++-7 -y && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-7 && \
    update-alternatives --config gcc

#WORKDIR /
#RUN git clone --recursive https://github.com/supershinyeyes/redner.git 
COPY redner /app
WORKDIR /app
RUN chmod -R a+w /app
ARG OPTIX_VERSION=6.0.0
COPY dependencies/NVIDIA-OptiX-SDK-${OPTIX_VERSION}-linux64 /usr/local/optix
ENV LD_LIBRARY_PATH /usr/local/optix/lib64:${LD_LIBRARY_PATH}

# Build Redner
RUN mkdir build && \
    cd build && \
    cmake .. && \
    make install -j 8 
```

**Comment by SuperShinyEyes** [comment]
I just tried with embree 3.5.0 and 3.2.4 and they both generate the same errors:
```bash
$ python 01_optimize_single_triangle.py 
Traceback (most recent call last):
  File "01_optimize_single_triangle.py", line 99, in <module>
    img = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context
```

**Comment by BachiLi** [comment]
Do you know which lines it fails?

**Comment by SuperShinyEyes** [comment]
> Do you know which line it fails?

@BachiLi Are you asking me? It's the line in `render_pytorch.py` as it is shown in my comment above.
```
Traceback (most recent call last):
  File "01_optimize_single_triangle.py", line 99, in <module>
    img = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context
```

**Comment by SuperShinyEyes** [comment]
All tutorials failed with the same error:
```bash
$ python 01_optimize_single_triangle.py 
Traceback (most recent call last):
  File "01_optimize_single_triangle.py", line 99, in <module>
    img = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context

$ python 02_pose_estimation.py 
Traceback (most recent call last):
  File "02_pose_estimation.py", line 84, in <module>
    img = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context

$ python 04_fast_deferred_rendering.py 
Traceback (most recent call last):
  File "04_fast_deferred_rendering.py", line 73, in <module>
    g_buffer = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context

$ python 05_coarse_to_fine_estimation.py 
Traceback (most recent call last):
  File "05_coarse_to_fine_estimation.py", line 28, in <module>
    img = render(0, *scene_args)
  File "/opt/conda/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 276, in forward
    pyredner.get_use_gpu())
RuntimeError: Invalid context
```

**Comment by BachiLi** [comment]
@SuperShinyEyes Well both of you. The render function calls the C++ code in pathtracer.cpp. Do you know which line in C++ that throws the runtime error?

**Comment by SuperShinyEyes** [comment]
@BachiLi I've never worked with Python code integrating C++. Could you guide me how to debug?

**Comment by BachiLi** [comment]
Maybe try:
gdb python
run 01_optimize_single_triangle.py

**Comment by SuperShinyEyes** [comment]
@BachiLi Okay. I will try next week(I work on Mondays and Tuesdays).

**Comment by jpchen** [comment]
so i tried building without cuda and running an example still fails with that error. the error is caused by the python stack trace i posted above when `envmap` is `None`.

```
#0  __cxxabiv1::__cxa_throw (obj=obj@entry=0x555557acd9a0, tinfo=tinfo@entry=0x7fff8fffc3c0 <typeinfo for optix::prime::Exception>, dest=dest@entry=0x7fff8f6c8ea0 <optix::prime::Exception::~Exception()>) at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:80
#1  0x00007fff8f76296b in optix::prime::checkError (code=RTP_ERROR_UNKNOWN, context=<optimized out>) at /home/jpchen/Downloads/NVIDIA-OptiX-SDK-6.0.0-linux64/include/optix_prime/optix_primepp.h:741
#2  0x00007fff8f75976f in optix::prime::ContextObj::ContextObj (type=RTP_CONTEXT_TYPE_CUDA, this=0x555557ad0920) at /home/jpchen/Downloads/NVIDIA-OptiX-SDK-6.0.0-linux64/include/optix_prime/optix_primepp.h:396
#3  optix::prime::ContextObj::create (type=RTP_CONTEXT_TYPE_CUDA) at /home/jpchen/Downloads/NVIDIA-OptiX-SDK-6.0.0-linux64/include/optix_prime/optix_primepp.h:375
#4  optix::prime::Handle<optix::prime::ContextObj>::create (type=RTP_CONTEXT_TYPE_CUDA) at /home/jpchen/Downloads/NVIDIA-OptiX-SDK-6.0.0-linux64/include/optix_prime/internal/Handle.h:74
#5  Scene::Scene (this=0x555557ad0580, camera=..., shapes=..., materials=..., area_lights=..., envmap=..., use_gpu=true) at /home/jpchen/3d-scene-gen/path_tracer/redner/scene.cpp:76
#6  0x00007fff8f6e2edb in pybind11::detail::initimpl::construct_or_initialize<Scene, Camera const&, std::vector<Shape const*, std::allocator<Shape const*> > const&, std::vector<Material const*, std::allocator<Material const*> > const&, std::vector<AreaLight const*, std::allocator<AreaLight const*> > const&, std::shared_ptr<EnvironmentMap const> const&, bool, 0>(Camera const&, std::vector<Shape const*, std::allocator<Shape const*> > const&, std::vector<Material const*, std::allocator<Material const*> > const&, std::vector<AreaLight const*, std::allocator<AreaLight const*> > const&, std::shared_ptr<EnvironmentMap const> const&, bool&&) ()
    at /home/jpchen/miniconda2/envs/graphics-cuda/include/python3.6m/pybind11/detail/init.h:61

(gdb) list
75	in /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc
```

i'm not sure where that path is coming from i dont even have a `/opt/conda/` directory.

**Comment by BachiLi** [comment]
Thanks. I'm using optix 5.1.
Seems that CUDA is not properly disabled/enabled in both cases. The error is from Optix prime, stating that it fails to initialize. Are you able to run the optix prime examples in the optix SDK?

**Comment by jpchen** [comment]
so after a fair bit of debugging it turns out that optix 6.0 only works with a 418 driver or higher, so updating my driver did the trick (presumably downgrading optix would work as well).  @BachiLi it would be enormously helpful if you posted the version numbers of the dependencies redner uses and is tested on.  thanks for your help debugging this!

**Comment by BachiLi** [comment]
Well this particular case seems to be at Optix (or NVIDIA)'s fault...but yeah thanks for reporting and sorry for the frustratoin ; )

**Comment by SuperShinyEyes** [comment]
I downgraded my Optix to 5.1 from 6.0, and it works now. Thank you two for the help :)
